<?php

/**
 * @file
 * Test module for Filter module hooks and functions not used in core.
 */

/**
 * Implements HOOK_filter_format_insert().
 */
function filter_test_filter_format_insert($format) {
  drupal_set_message('HOOK_filter_format_insert invoked.');
}

/**
 * Implements HOOK_filter_format_update().
 */
function filter_test_filter_format_update($format) {
  drupal_set_message('HOOK_filter_format_update invoked.');
}

/**
 * Implements HOOK_filter_format_disable().
 */
function filter_test_filter_format_disable($format) {
  drupal_set_message('HOOK_filter_format_disable invoked.');
}
